### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by ckdextergames** [CrystalFerrai/IcarusResourceRespawn#1]
Understand if you can't help out with this. Just thought I'd share the error I got:

Took me a while to figure out how to properly escape the space character in the name of my prospect, but once I did, I got this back:

PS C:\Users\CK_Dexterhaven\Documents\ICARUS_MODDING\IcarusResourceRespawn-1.0.0\IcarusResourceRespawn> .\IcarusResourceRespawn 'C:\Users\CK_Dexterhaven\AppData\Local\Icarus\Saved\PlayerData\76561199157448515\Prospects\THE EXPANSE.json'
Loading prospect...
Modifying prospect...
Unhandled exception. System.InvalidOperationException: Instance is not valid for serialization
   at UeSaveGame.PropertyTypes.ArrayProperty.Serialize(BinaryWriter writer, Boolean includeHeader)
   at UeSaveGame.UProperty.Serialize(BinaryWriter writer)
   at UeSaveGame.Util.PropertySerializationHelper.WriteProperties(IEnumerable`1 properties, BinaryWriter writer, Boolean isNullTerminated)
   at UeSaveGame.StructData.PropertiesStruct.Serialize(BinaryWriter writer)
   at UeSaveGame.PropertyTypes.StructProperty.Serialize(BinaryWriter writer, Boolean includeHeader)
   at UeSaveGame.Util.ArraySerializationHelper.Serialize(BinaryWriter writer, FString itemType, Boolean includeHeader, StructProperty prototype, IReadOnlyList`1 inData)
   at UeSaveGame.PropertyTypes.ArrayProperty.Serialize(BinaryWriter writer, Boolean includeHeader)
   at UeSaveGame.UProperty.Serialize(BinaryWriter writer)
   at UeSaveGame.Util.PropertySerializationHelper.WriteProperties(IEnumerable`1 properties, BinaryWriter writer, Boolean isNullTerminated)
   at UeSaveGame.StructData.PropertiesStruct.Serialize(BinaryWriter writer)
   at UeSaveGame.PropertyTypes.StructProperty.Serialize(BinaryWriter writer, Boolean includeHeader)
   at UeSaveGame.UProperty.Serialize(BinaryWriter writer)
   at UeSaveGame.Util.PropertySerializationHelper.WriteProperties(IEnumerable`1 properties, BinaryWriter writer, Boolean isNullTerminated)
   at IcarusSaveLib.ProspectSerlializationUtil.SerializeRecorderData(IEnumerable`1 properties)
   at IcarusResourceRespawn.Program.UpdateProspeect(String path, TextWriter outputLog, TextWriter errorLog, TextWriter warningLog)
   at IcarusResourceRespawn.Program.Main(String[] args)

**Comment by CrystalFerrai** [comment]
Can you share your prospect json file?

**Comment by ckdextergames** [comment]
Sure thing. https://github.com/ckdextergames/stuff/blob/main/THE%20EXPANSE.json

**Comment by CrystalFerrai** [comment]
Thanks. It looks like the issue was that I published a bad build of the program somehow. I rebuilt and published a 1.0.1 [release](https://github.com/CrystalFerrai/IcarusResourceRespawn/releases) which seems to be working fine.

**Comment by ckdextergames** [comment]
Cool! Thx I'll retry now

**Comment by ckdextergames** [comment]
Worked perfectly! THANK YOU!
